language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t liycy067/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true liycy067/docker-react npm run test -- --coverge
